version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - serverless-app
    command: mongod --bind_ip 0.0.0.0

  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 5050:5050
    volumes:
      - ./:/root/app
      - ~/.aws:/root/.aws
    networks:
      - serverless-app
    command: npm run start:docker

volumes:
  mongodb:


networks:
  serverless-app:
    driver: bridge
